#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check for the BYPASS_HOOK variable to bypass the hook
if [ "$BYPASS_HOOK" = "true" ]; then
  exit 0
fi

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)
VERSION_CHANGE_REGEX="^(Patch|Minor|Major)"

if ! echo "$COMMIT_MSG" | grep -E "$VERSION_CHANGE_REGEX"; then
  echo "Error: Commit message must start with 'Patch', 'Minor', or 'Major'."
  exit 1
fi

# Execute the Node.js script with the path to the temporary commit message file
node scripts/pre-commit-version-change.mjs "$COMMIT_MSG_FILE"

# Capture the exit status of the Node.js script
EXIT_STATUS=$?

# Check if the Node.js script executed successfully
if [ $EXIT_STATUS -eq 0 ]; then
  # Add package.json to the staging area
  git add package.json

  # Use an environment variable to bypass the hook for the next commit
  BYPASS_HOOK=true git commit -m "Auto-commit: Version bump in package.json"

  # Reset the BYPASS_HOOK variable
  unset BYPASS_HOOK
fi

# Exit with the captured exit status
exit $EXIT_STATUS
