#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Retrieve the last commit message
COMMIT_MSG=$(git log -1 --pretty=%B)

VERSION_CHANGE_REGEX="^(Patch|Minor|Major)"

if ! echo "$COMMIT_MSG" | grep -E "$VERSION_CHANGE_REGEX"; then
  echo "Error: Commit message must start with 'Patch', 'Minor', or 'Major'."
  exit 1
fi

# Execute the Node.js script. Pass the commit message as an argument if needed.
node scripts/pre-commit-version-change.mjs "$COMMIT_MSG"

# Capture the exit status of the Node.js script
EXIT_STATUS=$?

# Check if the Node.js script executed successfully
if [ $EXIT_STATUS -eq 0 ]; then
  # Stage the package.json changes
  git add package.json
  
  # Commit the changes with --no-verify to bypass the hooks
  git commit --no-verify -m "Version bump in package.json"
fi

# Exit with the captured exit status
exit $EXIT_STATUS
